config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :equipments do
    resources :bookings, except: [:destroy]
  end
  get 'dashboard/equipments', to: 'dashboards#my_equipments', as: :dashboard_equipments
  get 'dashboard/bookings', to: 'dashboards#my_bookings', as: :dashboard_bookings

  post '/search', to: 'equipments#search', as: :equipments_search

  root to: 'equipments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :equipment
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  self.table_name = 'equipments'
  SHAPES = ["(like) new", "very good shape", "a few bumps and scratches", "a bit old"]
  SIZES = ["37", "37.5", "38", "38.5", "39", "39.5", "40", "40.5", "41", "41.5", "42", "42.5", "43", "43.5", "44", "44.5", "45", "45.5", "46"]

  validates :title, presence: true
  validates :photo, presence: true
  validates :size, presence: true
  validates :shape, presence: true
  validates :daily_price, presence: true
  validates :location, presence: true

  validates :shape, inclusion: { in: SHAPES }
  validates :size, inclusion: { in: SIZES }

  belongs_to :user
  has_many :bookings

  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :equipments
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end

  def create
    @equipment = Equipment.find(params[:equipment_id])
    authorize @equipment

    @booking = Booking.new(review_params)
    authorize @booking
    @booking.equipment = @equipment
    @booking.price = @equipment.daily_price.to_i * ((@booking.end_date.to_date - @booking.start_date.to_date).to_i)
    @booking.status = "Pending"
    @booking.user = current_user
    if @booking.save
      redirect_to dashboard_bookings_path
    else
      render 'equipments/show'
    end
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if params[:commit] == "Accept"
      if @booking.update(status: "Accepted")
        redirect_to dashboard_bookings_path
      else
        render :my_bookings
      end
    elsif params[:commit] == "Decline"
      if @booking.update(status: "Declined")
        redirect_to dashboard_bookings_path
      else
        render :my_bookings
      end
    elsif params[:commit] == "Cancel"
      if @booking.update(status: "Cancelled")
        respond_to do |format|
          format.html { redirect_to dashboard_bookings_path }
          format.js
        end
      else
        render :my_bookings
      end
    end
  end


  private

  def review_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  skip_after_action :verify_authorized
  after_action :verify_policy_scoped

  def my_equipments
    authorize :dashboard, :my_equipments?
    @equipments = policy_scope(Equipment).where(user: current_user)
  end

  def my_bookings
    authorize :dashboard, :my_bookings?
    @bookings_sent = policy_scope(Booking).where(user: current_user)
    @bookings_received = Booking.all.select do |booking|
      booking.equipment.user == current_user
    end
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_equipments, only: [:index, :new, :create, :show]

  def index
  end

  def show
    @equipment = Equipment.find(params[:id])
    @booking = Booking.new
    authorize @equipment
  end

  def new
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    @equipment.user = current_user
    authorize @equipment
    if @equipment.save
      redirect_to dashboard_equipments_path
    else
      render :new
    end
  end

  def search
    @equipments = Equipment.where("location ILIKE ?", params[:location]).where("size ILIKE ?", params[:size])
    authorize @equipments
    render :index
  end

  private

  def set_equipments
    @equipments = policy_scope(Equipment)
  end

  def equipment_params
    params.require(:equipment).permit(:title, :description, :size, :shape, :daily_price, :photo, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/update.js.erb
function refreshForm(form) {
  const booking = document.querySelector("[data-booking-id='<%= @booking.id %>']");
  booking.innerHTML = form;
  console.log(booking);
}

refreshForm('<%= j render "dashboards/form", booking: @booking %>');

app/views/dashboards/_form.html.erb
<%= booking.status.upcase %>
  <% if Date.today < booking.start_date.to_date - 2.day && booking.status.upcase != 'CANCELLED' %>
    <%= simple_form_for [booking.equipment, booking] , method: :patch, remote: true do |f| %>
    <%= f.button :submit, value: 'Cancel', class:"btn btn-cancel" %>
    <% end %>
  <% end %>

app/views/dashboards/my_bookings.html.erb
<div class="container body extension">
  <br>
  <h2 class="text-center">My Bookings</h2>

  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Received</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Sent</a>
    </li>

  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      <% @bookings_received.each do |booking| %>
      <div class="card-category">
        <p><%= cl_image_tag booking.equipment.photo, class:"tabs-img" %></p>
        <div class="date">
          <p>From: <%= booking.start_date %></p>
          <p>To: <%= booking.end_date %></p>
        </div>
        <div class="price">
          <p>Price: <%= booking.price %>€</p>
        </div>
        <div class="booking-status">
          <p class="pending"><%= booking.status.upcase %></p>
          <% if booking.status.upcase == "PENDING" %>
            <%= simple_form_for [booking.equipment, booking] , method: :patch do |f| %>
              <%= f.button :submit, value: 'Accept', class:"btn btn-accepted" %>
            <% end %>
            <%= simple_form_for [booking.equipment, booking] , method: :patch do |f| %>
              <%= f.button :submit, value: 'Decline', class:"btn btn-declined" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <% @bookings_sent.each do |booking| %>
        <div class="card-category ">
          <p><%= cl_image_tag booking.equipment.photo, class:"tabs-img" %></p>
          <div class="date">
            <p>From: <%= booking.start_date %></p>
            <p>To: <%= booking.end_date %></p>
          </div>
          <div class="price">
          <p>Price: <%= booking.price %>€</p>
        </div>
          <div class="booking-status">
            <div data-booking-id="<%= booking.id%>">
              <%= render 'form', booking: booking %>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboards/my_equipments.html.erb
<div class="container body extension">
  <div id="equipments-list" class="cards-container">
    <br>
    <h2 class="text-center">My Equipment</h2>
    <div class="row cards">
      <% @equipments.each do |equipment| %>
        <%= link_to equipment_path(equipment.id), class:"roller-card" do %>
          <!-- <div class="col-xs-12 col-sm-6 col-md-4"> -->
            <div class="roller-image">
              <%= cl_image_tag(equipment.photo, height: 250, width: 250,crop: :fill) %>
            </div>
            <div class="roller-text">
              <div class="title-size">
                <h4><%= equipment.title %></h4>
                <p>Size: <%= equipment.size %></p>
              </div>
              <div class="location-price">
                <p><%= equipment.location %></p>
                <p><%= equipment.daily_price %>€/day</p>
              </div>
            </div>
          <!-- </div> -->
        <% end %>
      <% end %>
    </div>
      <%= link_to 'Add equipment', new_equipment_path, class:'btn btn-gradient' %>
    <br>
    <br>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container body">
  <div id="equipments-list" class="cards-container">
    <br>
    <h2 class="text-center">My Equipments</h2>
    <div class="row cards">
      <% @equipments.each do |equipment| %>
        <%= link_to equipment_path(equipment.id), class:"roller-card" do %>
          <!-- <div class="col-xs-12 col-sm-6 col-md-4"> -->
            <div class="roller-image">
              <%= cl_image_tag(equipment.photo, height: 250, width: 250,crop: :fill) %>
            </div>
            <div class="roller-text">
              <div class="title-size">
                <h4><%= equipment.title %></h4>
                <p>Size: <%= equipment.size %></p>
              </div>
              <div class="location-price">
                <p><%= equipment.location %></p>
                <p><%= equipment.daily_price %>€/day</p>
              </div>
            </div>
          <!-- </div> -->
        <% end %>
      <% end %>
    </div>
      <%= link_to 'Add equipment', new_equipment_path, class:'btn btn-gradient' %>
    <br>
    <br>
  </div>
</div>

app/views/equipments/_form.html.erb
<div class="container body equipment-book form-center">
    <%= simple_form_for ([@equipment, @booking]) do |f| %>
      <%= f.input :start_date, as: :string, required: true, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: true, input_html: {class: "datepicker"} %>
      <%= f.button :submit, "Book",  class: 'btn-gradient' %>
    <% end %>
</div>

app/views/equipments/_user-equipment.html.erb
<div class="user-card text-center">
  <p><%= cl_image_tag @equipment.user.photo, class: "avatar-large" %></p>
  <p>Rent those Roller from: <br><span class="bold"><%= @equipment.user.username.upcase %><span></p>
</div>

app/views/equipments/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'roller-banner.png' %>');">
  <div class="container body">
    <h1><strong>Welcome to DecathLoc'</strong></h1>
    <p>The platform to rent Blades, for your trainings or competitions</p>
    <div class="search-bar">
    <%= form_tag equipments_search_path, html: {class: "form-inline"} do %>
      <%= text_field_tag :location, "", class:"search-input", placeholder:"Enter your city" %>
      <%= select_tag "size", options_for_select(Equipment::SIZES, "Size"), class: 'select2 search-input', placeholder:"Size" %>
    </div>
      <%= submit_tag("LOC", {class:"btn btn-gradient"}) %>
    <% end %>
  </div>
</div>
<div class="container">
  <div id="equipments-list">
    <div class="row cards">
      <% @equipments.each do |equipment| %>
        <%= link_to equipment_path(equipment.id), class:"roller-card" do %>
            <div class="roller-image">
              <%= cl_image_tag(equipment.photo, height: 250, width: 250,crop: :fill) %>
            </div>
            <div class="roller-text">
              <div class="title-size">
                <h4><%= equipment.title %></h4>
                <p>Size: <%= equipment.size %></p>
              </div>
              <div class="location-price">
                <p><%= equipment.location %></p>
                <p><%= equipment.daily_price %>€/day</p>
              </div>
            </div>
        <% end %>
      <% end %>
    </div>
    <br>
  </div>
</div>

app/views/equipments/new.html.erb
<div class="container">
  <div class="form-container body">
    <div class="row form-center">
      <div class="col-xs-12 col-sm-6 col-md-offset-3">


        <%= simple_form_for @equipment, url: equipments_path do |f| %>
        <h2 class="text-center">Add quad rollers for rent</h2>
          <div class="form-inputs">
            <%= f.input :title,
                        autofocus: true %>
            <%= f.input :description,
                        autofocus: true %>
            <%= f.input :size,
                        collection: Equipment::SIZES,
                        input_html: { class: 'select2' } %>
            <%= f.input :shape,
                        collection: Equipment::SHAPES,
                        input_html: { class: 'select2' } %>
            <%= f.input :location,
                        autofocus: true %>
            <%= f.input :daily_price,
                        autofocus: true %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
          </div>

          <div class="form-actions btn-form">
            <%= f.button :submit, "Let's roll!", class:"btn-gradient" %>
          </div>
        <% end %>
        <br>

      </div>
    </div>
  </div>
</div>

app/views/equipments/show.html.erb
<div class="container body extension">
  <div class="row equipment-show-book">
    <div class="big-card d-inline-flex">
      <div class="equipment-img">
        <%= cl_image_tag @equipment.photo, width: 280, height: 280, crop: :thumb, gravity: :face %>
      </div>
      <div class="equipment-desc">
        <h2><%= @equipment.title %></h2>
        <p>Description: <%= @equipment.description %></p>
        <p>Size: <%= @equipment.size %></p>
        <p>Shape: <%= @equipment.shape %></p>
        <p>Daily Price: <%= @equipment.daily_price %>€</p>
        <p>Location: <%= @equipment.location %></p>
      </div>
    </div>
    <div class="user-booking">
      <div class>
        <% if current_user != @equipment.user %>
        <%= render 'user-equipment', equipment: @equipment %>
        <% end %>
      </div>
      <div class="form-card">
        <% if current_user != @equipment.user %>
        <%= render 'form', booking: @booking, equipment: @equipment %>
        <% end %>
      </div>
    </div>
  </div>
  <br>
</div>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

     <%= favicon_link_tag asset_path('favicon.png') %>
    <title>DECATHLOC'</title>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <% if user_signed_in? %>
      <% if current_user.equipment_ids.empty? %>
        <%= render 'shared/current-user-navbar' %>
      <% else %>
        <%= render 'shared/user-with-equipments-navbar' %>
      <% end %>
    <% else %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_current-user-navbar.html.erb
<div class="navbar-decathloc sticky">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "decathloc-logo.png", class: "logo-tag" %>
    <% end %>
  </div>

  <!-- displayed on laptops -->
  <div class="navbar-decathloc-actions d-none d-sm-flex">
    <%= link_to 'MY BOOKINGS', dashboard_bookings_path, class: "active" %>
    <%= link_to 'ADD EQUIPMENT', new_equipment_path, class: "active" %>
    <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "active" %>
    <%= cl_image_tag current_user.photo, class: "avatar" %>
  </div>

  </div>

  <!-- displayed on phone / tablet -->
  <div class="navbar-decathloc-actions d-block d-sm-none">
    <div class="dropdown">
      <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to 'MY BOOKINGS', dashboard_bookings_path, class: "dropdown-item" %>
        <%= link_to 'ADD EQUIPMENT', new_equipment_path, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer-container" class="footer navbar-fixed-bottom">
  <div class="footer-links">
    <a href="https://github.com/Maxlafitte/decathloc" target="blank"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    <h4>@Derby Team</h4>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-decathloc sticky">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "decathloc-logo.png", class: "logo-tag" %>
    <% end %>
  </div>

  <!-- displayed on laptops -->
  <div class="navbar-decathloc-actions d-none d-sm-flex">
    <%= link_to 'SIGN UP', new_user_registration_path %>
    <%= link_to 'LOG IN', new_user_session_path %>
  </div>

</div>

  <!-- displayed on phone / tablet -->
  <div class="navbar-decathloc-actions d-block d-sm-none">
    <div class="dropdown">
      <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to 'SIGN UP', new_user_registration_path, class: "dropdown-item" %>
        <%= link_to 'LOG IN', new_user_session_path, class: "dropdown-item" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user-with-equipments-navbar.html.erb
<div class="navbar-decathloc sticky">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "decathloc-logo.png", class: "logo-tag" %>
    <% end %>
  </div>

  <!-- displayed on laptops -->
  <div class="navbar-decathloc-actions d-none d-sm-flex">
    <%= link_to 'MY BOOKINGS', dashboard_bookings_path, class: "active" %>
    <%= link_to 'MY EQUIPMENT', dashboard_equipments_path, class: "active" %>
    <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class: "active" %>
    <%= cl_image_tag current_user.photo, class: "avatar" %>
  </div>

  </div>

  <!-- displayed on phone / tablet -->
  <div class="navbar-decathloc-actions d-block d-sm-none">
    <div class="dropdown">
      <i class="fas fa-bars" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
        <%= link_to 'MY BOOKINGS', dashboard_bookings_path, class: "dropdown-item" %>
        <%= link_to 'MY EQUIPMENT', dashboard_equipments_path, class: "dropdown-item" %>

      </div>
    </div>
  </div>
</div>